### PR TITLE
Introduce AgentsRegistry for integration with external agents providers

### PR DESCRIPTION
**Pull request by mariofusco**
## Issue

Closes #

## Change

This is a complete rework of the `AgentRegistry` implemented by this pull request github.com/langchain4j/langchain4j/pull/5551

The scope of this second implementation is quite different and less invasive than the original one since it doesn't care of providing a mechanism for dynamic discovery and rewiring of agents for an ongoing execution, but only to provide a thin layer of integration with external agents providers.

The new section added to the documentation should better clarify how this works.

## General checklist

- [X] There are no breaking changes (API, behaviour)
- [X] I have added unit and/or integration tests for my change
- [X] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by mariofusco** [comment]
@carlesarnal Please give a look at this second implementation. I believe that the other one was quite misleading since a dynamic discovery mechanism (that as you noted could work only for minimal and specific subset of all the agentic pattern available) shouldn't be a concern of the `AgentsRegistry`.

My suggestion is to try to reimplement your Apicurio integration based on this SPI. I also added a new annotation to declaratively integrate an agent taken from a registry with other locally defined ones as you can see in one of my tests. 

Please provide some feedback about this new version and if it is ok for you I would close the old pull request in favor of this one.

File: langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+     */
+    <T> T getAgent(Class<T> agentType);
+
+    /**
+     * Loads the {@link AgentsRegistry} via {@link ServiceLoader}.
+     * Returns the first provider found, or an empty registry if none is available.
+     *
+     * @return the loaded registry
+     */
+    static AgentsRegistry get() {
```
Comment (glaforge) [inline langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java:44]: Hmmm... What if there are more than one `AgentRegistry`? 
We always return the first one?
Shouldn't we somehow aggregate them all or something?

File: langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+        ServiceLoader<AgentsRegistry> loader = ServiceLoader.load(AgentsRegistry.class);
```
Comment (glaforge) [inline langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java]: Should the result be cached, or it's on purpose that we reload (think classpath scanning etc) each time `get()` is called? Maybe we do want this _dynamicity_ aspect though (but maybe a `refresh()` method would make that more explicit if that's the goal)

File: langchain4j-agentic/src/main/java/dev/langchain4j/agentic/AgenticServices.java
Comment (glaforge) [inline langchain4j-agentic/src/main/java/dev/langchain4j/agentic/AgenticServices.java:73]: An idea: what if the various builders had a `.registry(myOwnRegistry)` method to override / declare explicitly which registry they want to use besides the SPI?

**Review by glaforge — COMMENTED** [review]
I shared a few thoughts on the case we have multiple registries available, on caching the lookup from the service loader, and on specifying explicitly a registry when defining the different agent workflows.

File: langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java (hunk 1 above)
Comment (mariofusco) [reply langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java:44]: That's a valid concern. The current implementation only allows to load one single `AgentsRegistry`. I will check if I can support more than one.

File: langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java (hunk 2 above)
Comment (mariofusco) [reply langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java]: Thanks, fixed.

File: langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java (hunk 1 above)
Comment (mariofusco) [reply langchain4j-agentic/src/main/java/dev/langchain4j/agentic/planner/AgentsRegistry.java:44]: Done.

File: langchain4j-agentic/src/main/java/dev/langchain4j/agentic/AgenticServices.java
Comment (mariofusco) [reply langchain4j-agentic/src/main/java/dev/langchain4j/agentic/AgenticServices.java:73]: This is a good idea, but for now out of scope for this pull request. I will reconsider this in a second stage.

**Comment by carlesarnal** [comment]
> @carlesarnal Please give a look at this second implementation. I believe that the other one was quite misleading since a dynamic discovery mechanism (that as you noted could work only for minimal and specific subset of all the agentic pattern available) shouldn't be a concern of the `AgentsRegistry`.
> 
> My suggestion is to try to reimplement your Apicurio integration based on this SPI. I also added a new annotation to declaratively integrate an agent taken from a registry with other locally defined ones as you can see in one of my tests.
> 
> Please provide some feedback about this new version and if it is ok for you I would close the old pull request in favor of this one.

This is much cleaner than the previous approach. The separation is IMO right, the registry is a lookup, not a planner concern. @RegistryAgent for declarative wiring is a nice touch.

I started updating the Apicurio implementation against this SPI and a few things came up:

Thread safety on LazyHolder.INSTANCE, it's a mutable static reassigned by refresh(), but not volatile. A thread calling get() during a concurrent refresh() could see stale state.

getAgent(Class<T>) and remote agents, agents discovered from an external registry (A2A agent cards) won't have meaningful Java types. They'll all be UntypedAgent/Object, so getAgent(Class<T>) will match the first one arbitrarily. Not a blocker since getAgent(String name) is the natural path for registry-backed agents, but worth documenting.

ServiceLoader vs CDI, it works fine, and I don't have a problem with it, but this is a "classic" problem, in Quarkus, beans are CDI-managed, so AgentsRegistry.get() via ServiceLoader.load() won't find a CDI-registered implementation. We'll need to either generate a META-INF/services file at build time or add a setter/alternative discovery path. Not a problem with this PR — just something I need to handle on the Quarkus side.

No refresh trigger — refresh() is there but nothing calls it. For an external registry like Apicurio where agent cards change over time, the implementation has to decide when to call it (periodic timer, webhook, etc.). Fine as-is since that's an implementation concern, but as other elements might be worth mentioning in the docs.

Overall LGTM — go ahead and close the old PR.

**Comment by mariofusco** [comment]
@carlesarnal I agree with your comments so I made the `LazyHolder.INSTANCE` volatile and I removed the possibility to lookup an agent by class, that indeed for remote agents doesn't make much sense.

If I understand correctly the other 2 remarks are not directly related with this pull request, but something that has to be managed at the Quarkus extension level. If I'm right and I'm not missing anything I believe that this should be ready to be merged now, please let me know if it is ok for you.

**Comment by carlesarnal** [comment]
> @carlesarnal I agree with your comments so I made the `LazyHolder.INSTANCE` volatile and I removed the possibility to lookup an agent by class, that indeed for remote agents doesn't make much sense.
> 
> If I understand correctly the other 2 remarks are not directly related with this pull request, but something that has to be managed at the Quarkus extension level. If I'm right and I'm not missing anything I believe that this should be ready to be merged now, please let me know if it is ok for you.


Looks good, thanks for the quick fixes. 

You're correct that the ServiceLoader/CDI and refresh trigger are Quarkus-side concerns, I just wanted to rise them for awareness. OK from me to the merge.

**Review by carlesarnal — APPROVED** [review]

**Review by dliubarskyi — APPROVED** [review]
@mariofusco thank you! Some minor things if you want to address in a separate PR: 

🟠 AgentsRegistry.java:312 — CompositeAgentsRegistry.allAgents() returns the mutable internal HashMap, violating its own interface contract.
  The interface Javadoc (line 247) promises "an unmodifiable map of agent names to AgentInstances", and EmptyAgentsRegistry honors this with Map.of(). But the composite returns mergedAgents (a bare HashMap)
  directly, so any caller can put()/clear() and silently corrupt the shared registry for every subsequent lookup. Wrap the return in Collections.unmodifiableMap(...) (or Map.copyOf in the constructor).

  🟠 AgentsRegistry.java:280 / 289–293 — a failing discovery (e.g. duplicate names) permanently poisons the holder with ExceptionInInitializerError.
  LazyHolder.INSTANCE = discover() runs inside the static field initializer. If discover() throws — which the CompositeAgentsRegistry constructor does on duplicate agent names (line 305) — the first access to
  the holder fails with ExceptionInInitializerError, and every later get()/refresh() throws NoClassDefFoundError (an Error, not a recoverable exception) for the life of the classloader, even after the offending
  provider is removed. The docs sell this as "duplicate agent names cause an exception at discovery time", implying something catchable. The unit test only passes because earlier tests initialize the holder
  successfully first. Consider doing discovery in get()/refresh() outside the static initializer (or catching and deferring), so a bad provider surfaces a plain RuntimeException and stays recoverable.

  🟡 AgentsRegistryIT.java:432 (setUp) — the IT relies on get() doing fresh discovery but never calls refresh() after swapping the context classloader.
  get() returns the cached LazyHolder.INSTANCE. setUp sets the context classloader but doesn't refresh(), so the IT only works if the registry was never initialized earlier in the same JVM. If any prior code in
  the fork/JVM triggered AgentsRegistry.get() (which AgentsRegistryTest does, leaving it as the empty registry), this IT sees a stale empty registry and containsKeys("audienceEditor", "styleEditor") fails.
  AgentsRegistryTest correctly calls refresh() after switching classloaders — AgentsRegistryIT.setUp should do the same for robustness.

  Minor / non-blocking (no change required):
  - 🟡 The @RegistryAgent declarative path ignores the annotated method's @V parameters — binding comes entirely from the registry agent's own AgentInstance signature (via agentToExecutor(InternalAgent)). It
  works in the test because the keys happen to match; a mismatch would be silently ignored rather than reported. Worth a doc note that the interface method signature is illustrative only.
  - Raw RuntimeException is thrown for not-found/duplicate cases, whereas nearby code (agentToExecutor) uses IllegalArgumentException. A more specific type would read more consistently.
  - AgentsRegistry lives in the ...planner package despite being general-purpose (not planner-specific) — fine if intentional, but slightly surprising placement.
